In [1]:
import pandas as pd

ur1 = 'https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv'
data = pd.read_csv(ur1)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [2]:
data['EducationLevel'] = data['EducationLevel'].map({'高中以下':0, '大學':1, '碩士以上':2}) #這樣可以把文字替換成數字
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [3]:
from sklearn.preprocessing import OneHotEncoder #OneHotEncoder可以幫我們快速地做轉換

onehot_encoder = OneHotEncoder() #創建一個編碼器
onehot_encoder.fit(data[['City']]) #讓這個編碼器去看過city這個特徵 但只接受傳入的是一個二為矩陣 用兩對中括號就會是二維矩陣
city_encoded = onehot_encoder.transform(data[['City']]).toarray() #讓他去做轉換 裡面資料一樣要是二維矩陣 不加toarray()只會回傳稀疏矩陣 要完整矩陣要加上這個
city_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [4]:
data[['CityA', 'CityB', 'CityC']]  = city_encoded # 想要幫他多加三列(直的,因為多三個特徵)
data

YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [5]:
data = data.drop(['City', 'CityC'], axis = 1) #刪掉多餘的列 列是axis = 1, 行是axis = 0
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [6]:
from sklearn.model_selection import train_test_split #分測試集和訓練集

x = data[['YearsExperience', 'EducationLevel', 'CityA', 'CityB']]#先把x,y分出來

y = data["Salary"]



x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state= 87) #第一個參數傳入特徵x 第二個參數傳入y 後面那0.2會自動把2成分出來當測試集 這會回傳4個值
#random_state= 87 是讓他分割的時候固定 只要是87 就不管分割幾次結果都會一樣


x_train = x_train.to_numpy()  #轉換成numpy的格式 就是矩陣 後續計算會方便
x_test = x_test.to_numpy()

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(x_train) #只能讓他看訓練集的資料 不能給他看測試集的資料 這邊會算出來標準差和平均 此結果也會用在測試集上
x_train = scaler.transform(x_train) #做轉換
x_test = scaler.transform(x_test) #測試集就不用再額外去算測試集的標準差or平均 會直接使用訓練集擬合出來的結果



In [8]:
import numpy as np

w = np.array([1, 2, 3, 4]) #先設定w,b的值 因為w有四個 所以用一維矩陣來表示 這矩陣有4個值
b = 0
y_pred = (x_train*w).sum(axis = 1) +b# x_train*w = [w1*第一列 ,w2*第二列, w3*第三列, w4*第四列] / axis = 1就是橫向作加總 =0就是直的做加總
# y_pred 就是我們預測出來的薪水 下一步就是要找最適合的w and b

In [9]:
((y_train - y_pred)**2).mean()

2830.761648680892

In [10]:
def compute_cost(x, y, w, b):
  y_pred = (x*w).sum(axis = 1) +b
  cost = ((y - y_pred)**2).mean()
  return cost

In [11]:
w = np.array([0, 2, 2, 4]) #先設定w,b的值 因為w有四個 所以用一維矩陣來表示 這矩陣有4個值
b = 0

compute_cost(x_train, y_train, w, b)

2822.234209806599

In [12]:
 y_pred = (x_train*w).sum(axis = 1) +b
 b_gradient = (y_pred - y_train).mean()

#x1 = x_train[:,0] 就是第一個特徵值
#x_train[:,0] #這樣可以只取得第一列 :是指地一個維度的值都要 0是指第二個維度的值只要最開始的那個 所以只會取得第一列所有值
w_gradient = np.zeros(x_train.shape[1]) #創建一個空矩陣 把四個斜率放在一起

for i in range(x_train.shape[1]):
  w_gradient[i] = (x_train[:,i] *(y_pred - y_train)).mean()

w_gradient
 #w1_gradient =  (x_train[:,0] *(y_pred - y_train)).mean()
 #w2_gradient =  (x_train[:,1] *(y_pred - y_train)).mean()
 #w3_gradient =  (x_train[:,2] *(y_pred - y_train)).mean()
 #w4_gradient =  (x_train[:,3] *(y_pred - y_train)).mean()

#w1_gradient, w2_gradient, w3_gradient, w4_gradient

array([ -6.35305402, -12.62906041,  10.23132015,  -1.76948291])

In [13]:
def compute_gradient(x, y, w, b):
  y_pred = (x*w).sum(axis = 1) +b
  w_gradient = np.zeros(x.shape[1]) #創建一個空矩陣 把四個斜率放在一起
  b_gradient = (y_pred - y).mean()
  for i in range(x.shape[1]):
    w_gradient[i] = (x[:,i] *(y_pred - y)).mean()

  return w_gradient, b_gradient



In [14]:
w = np.array([1, 2, 2, 4]) #先設定w,b的值 因為w有四個 所以用一維矩陣來表示 這矩陣有4個值
b = 1

compute_gradient(x_train, y_train, w, b)

(array([ -5.35305402, -12.20449464,   9.61677346,  -1.12136056]), -49.95)

In [15]:
learning_rate = 0.001
w = np.array([1, 2, 2, 4]) #先設定w,b的值 因為w有四個 所以用一維矩陣來表示 這矩陣有4個值
b = 1

w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)
print(compute_cost(x_train, y_train, w, b)) #看cost有無變小 更新前看一次

w = w - w_gradient * learning_rate #更新w方向的斜率
b = b - b_gradient * learning_rate

w, b
print(compute_cost(x_train, y_train, w, b)) #更新後看一次


2709.6281017583538
2704.098469896066


In [16]:
np.set_printoptions(formatter = {'float': '{: .2e}'.format}) #更改numpy的格式 =下面.2e的意思

def gradient_descent(x, y, a_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter = 1000):

  c_hist = [] #這三個列表就是拿來儲存 我們跑的每一次裡面的cost a and b 值
  a_hist = []
  b_hist = []

  a = a_init
  b = b_init

  for i in range(run_iter):
    a_gradient, b_gradient = gradient_function(x,y,a,b) #得到a,b斜率

    a = a - a_gradient*learning_rate # 得到更新後的a斜率
    b = b - b_gradient*learning_rate # 得到更新後的b斜率
    cost = cost_function(x,y,a,b)


    a_hist.append(a)
    b_hist.append(b)
    c_hist.append(cost)

    if i%p_iter == 0:
      print(f'Ieration {i: 6}: Cost: {cost: .4e}, a: {a}, b: {b: .2e}, a_gradient: {a_gradient}, b_gradient: {b_gradient: .2e}') # cost那邊的.2f是指只取到小數點後兩位/ i:6 是指佔用6格 這樣比較整齊

  return a, b, a_hist, b_hist, c_hist


In [17]:
w_init = np.array([1, 2, 2, 4])
b_init = 0
learning_rate = 1.0e-2 #這是科學記號的寫法 也就是0.001
run_iter = 10000


w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter)

Ieration      0: Cost:  2.7535e+03, a: [ 1.05e+00  2.12e+00  1.90e+00  4.01e+00], b:  5.10e-01, a_gradient: [-5.35e+00 -1.22e+01  9.62e+00 -1.12e+00], b_gradient: -5.10e+01
Ieration   1000: Cost:  2.5326e+01, a: [ 3.73e+00  1.39e+01 -1.82e+00 -3.51e+00], b:  5.09e+01, a_gradient: [-9.61e-02 -6.24e-02 -8.60e-02  7.25e-02], b_gradient: -2.20e-03
Ieration   2000: Cost:  2.5223e+01, a: [ 4.09e+00  1.41e+01 -1.49e+00 -3.76e+00], b:  5.09e+01, a_gradient: [-8.25e-03 -5.10e-03 -7.72e-03  5.60e-03], b_gradient: -9.50e-08
Ieration   3000: Cost:  2.5222e+01, a: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, a_gradient: [-6.98e-04 -4.34e-04 -6.57e-04  4.72e-04], b_gradient: -4.10e-12
Ieration   4000: Cost:  2.5222e+01, a: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, a_gradient: [-5.92e-05 -3.68e-05 -5.57e-05  4.00e-05], b_gradient: -3.48e-13
Ieration   5000: Cost:  2.5222e+01, a: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, a_gradient: [-5.02e-06 -3.12e-06 -4.73e

In [18]:
w_final, b_final #最終找到的w and b 接下來就是拿去給測試集看結果好不好

(array([ 4.12e+00,  1.41e+01, -1.46e+00, -3.78e+00]), 50.949999999999655)

In [19]:
y_pred = (w_final * x_test).sum(axis = 1) + b_final
pd.DataFrame({'y_pred': y_pred, 'y_test': y_test }) #轉乘pd的格式比較好看

y_pred  y_test
20  44.035070    43.8
16  67.440313    72.7
5   61.954972    60.8
27  23.802655    24.9
32  62.748179    56.3
2   23.485373    25.2
1   72.425307    80.5
7   68.074879    70.3

In [20]:
compute_cost(x_test, y_test, w_final, b_final)

18.116060544218655

In [21]:
# 有新人年資5.3年 碩士以上 城市A
#第二個人 7.2年 高中以下 城市B

x_real = np.array([[5.3, 2, 1, 0], [7.2, 0, 0, 1]]) #如果上面有做特徵縮放 這邊實際情況也要做 所以這邊再加一個[]使其變成二維矩陣
x_real = scaler.transform(x_real) # transform只接受傳入二為矩陣 不接受一維

y_real = (w_final * x_real).sum(axis = 1) + b_final #我們的模型是這樣計算的
y_real

array([ 6.55e+01,  2.34e+01])